spring.application.name=api

# ===============================
# Server
# ===============================
server.port=${SERVER_PORT:8080}

# ===============================
# Datasource - MySQL
# ===============================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/vounovolei}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# Logging SQL (opcional)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# ===============================
# JWT
# ===============================
security.jwt.secret=${JWT_SECRET:632598623952369865903003566748393365632799312}
security.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:15}
security.jwt.refresh-expiration-minutes=${JWT_REFRESH_EXPIRATION_MINUTES:10080}
security.jwt.forgot-password-expiration-minutes=${JWT_FORGOT_PASSWORD_EXPIRATION_MINUTES:10}


# Uploads
app.uploads.base-dir=${UPLOADS_BASE_DIR:uploads}
app.uploads.avatars-dir=${app.uploads.base-dir}/avatars
app.uploads.max-avatar-bytes=${UPLOADS_MAX_AVATAR_BYTES:2097152}

# limite multipart no Spring
spring.servlet.multipart.max-file-size=${MULTIPART_MAX_FILE_SIZE:2MB}
spring.servlet.multipart.max-request-size=${MULTIPART_MAX_REQUEST_SIZE:2MB}
